export const dataTablesData = [
	{ id:1,
      firstname: "James",
      lastname: "Smith",
      address:" b2-street#1  Houston",
    },
    { id:2,
      firstname: "James",
      lastname: "Smith",
      address:" b2-street#1  Houston",
    },
    { id:3,
      firstname: "James",
      lastname: "Smith",
      address:" b2-street#1  Houston",
    },
    { id:4,
      firstname: "James",
      lastname: "Smith",
      address:" b2-street#1  Houston",
    },
]